// { ja: 日本語名, en: 英語名（DB保存用） }
export const COUNTRIES = [
  { ja: 'アフガニスタン', en: 'Afghanistan' },
  { ja: 'アルバニア', en: 'Albania' },
  { ja: 'アルジェリア', en: 'Algeria' },
  { ja: 'アンゴラ', en: 'Angola' },
  { ja: 'アルゼンチン', en: 'Argentina' },
  { ja: 'アルメニア', en: 'Armenia' },
  { ja: 'オーストラリア', en: 'Australia' },
  { ja: 'オーストリア', en: 'Austria' },
  { ja: 'アゼルバイジャン', en: 'Azerbaijan' },
  { ja: 'バングラデシュ', en: 'Bangladesh' },
  { ja: 'ベラルーシ', en: 'Belarus' },
  { ja: 'ベルギー', en: 'Belgium' },
  { ja: 'ベリーズ', en: 'Belize' },
  { ja: 'ベナン', en: 'Benin' },
  { ja: 'ボリビア', en: 'Bolivia' },
  { ja: 'ボスニア・ヘルツェゴビナ', en: 'Bosnia and Herzegovina' },
  { ja: 'ブラジル', en: 'Brazil' },
  { ja: 'ブルネイ', en: 'Brunei' },
  { ja: 'ブルガリア', en: 'Bulgaria' },
  { ja: 'ブルキナファソ', en: 'Burkina Faso' },
  { ja: 'ブルンジ', en: 'Burundi' },
  { ja: 'カンボジア', en: 'Cambodia' },
  { ja: 'カメルーン', en: 'Cameroon' },
  { ja: 'カナダ', en: 'Canada' },
  { ja: '中央アフリカ共和国', en: 'Central African Republic' },
  { ja: 'チャド', en: 'Chad' },
  { ja: 'チリ', en: 'Chile' },
  { ja: '中国', en: 'China' },
  { ja: 'コロンビア', en: 'Colombia' },
  { ja: 'コンゴ共和国', en: 'Republic of the Congo' },
  { ja: 'コンゴ民主共和国', en: 'Democratic Republic of the Congo' },
  { ja: 'コスタリカ', en: 'Costa Rica' },
  { ja: 'コートジボワール', en: "Cote d'Ivoire" },
  { ja: 'クロアチア', en: 'Croatia' },
  { ja: 'キューバ', en: 'Cuba' },
  { ja: 'チェコ', en: 'Czech Republic' },
  { ja: 'デンマーク', en: 'Denmark' },
  { ja: 'ジブチ', en: 'Djibouti' },
  { ja: 'ドミニカ共和国', en: 'Dominican Republic' },
  { ja: 'エクアドル', en: 'Ecuador' },
  { ja: 'エジプト', en: 'Egypt' },
  { ja: 'エルサルバドル', en: 'El Salvador' },
  { ja: 'エチオピア', en: 'Ethiopia' },
  { ja: 'フィンランド', en: 'Finland' },
  { ja: 'フランス', en: 'France' },
  { ja: 'ガボン', en: 'Gabon' },
  { ja: 'ジョージア', en: 'Georgia' },
  { ja: 'ドイツ', en: 'Germany' },
  { ja: 'ガーナ', en: 'Ghana' },
  { ja: 'ギリシャ', en: 'Greece' },
  { ja: 'グアテマラ', en: 'Guatemala' },
  { ja: 'ギニア', en: 'Guinea' },
  { ja: 'ガイアナ', en: 'Guyana' },
  { ja: 'ハイチ', en: 'Haiti' },
  { ja: 'ホンジュラス', en: 'Honduras' },
  { ja: 'ハンガリー', en: 'Hungary' },
  { ja: 'インド', en: 'India' },
  { ja: 'インドネシア', en: 'Indonesia' },
  { ja: 'イラン', en: 'Iran' },
  { ja: 'イラク', en: 'Iraq' },
  { ja: 'アイルランド', en: 'Ireland' },
  { ja: 'イスラエル', en: 'Israel' },
  { ja: 'イタリア', en: 'Italy' },
  { ja: 'ジャマイカ', en: 'Jamaica' },
  { ja: '日本', en: 'Japan' },
  { ja: 'ヨルダン', en: 'Jordan' },
  { ja: 'カザフスタン', en: 'Kazakhstan' },
  { ja: 'ケニア', en: 'Kenya' },
  { ja: '北朝鮮', en: 'North Korea' },
  { ja: '韓国', en: 'South Korea' },
  { ja: 'クウェート', en: 'Kuwait' },
  { ja: 'キルギス', en: 'Kyrgyzstan' },
  { ja: 'ラオス', en: 'Laos' },
  { ja: 'レバノン', en: 'Lebanon' },
  { ja: 'リベリア', en: 'Liberia' },
  { ja: 'リビア', en: 'Libya' },
  { ja: 'マダガスカル', en: 'Madagascar' },
  { ja: 'マラウイ', en: 'Malawi' },
  { ja: 'マレーシア', en: 'Malaysia' },
  { ja: 'マリ', en: 'Mali' },
  { ja: 'モーリタニア', en: 'Mauritania' },
  { ja: 'メキシコ', en: 'Mexico' },
  { ja: 'モルドバ', en: 'Moldova' },
  { ja: 'モンゴル', en: 'Mongolia' },
  { ja: 'モロッコ', en: 'Morocco' },
  { ja: 'モザンビーク', en: 'Mozambique' },
  { ja: 'ミャンマー', en: 'Myanmar' },
  { ja: 'ナミビア', en: 'Namibia' },
  { ja: 'ネパール', en: 'Nepal' },
  { ja: 'オランダ', en: 'Netherlands' },
  { ja: 'ニュージーランド', en: 'New Zealand' },
  { ja: 'ニカラグア', en: 'Nicaragua' },
  { ja: 'ニジェール', en: 'Niger' },
  { ja: 'ナイジェリア', en: 'Nigeria' },
  { ja: 'ノルウェー', en: 'Norway' },
  { ja: 'オマーン', en: 'Oman' },
  { ja: 'パキスタン', en: 'Pakistan' },
  { ja: 'パナマ', en: 'Panama' },
  { ja: 'パプアニューギニア', en: 'Papua New Guinea' },
  { ja: 'パラグアイ', en: 'Paraguay' },
  { ja: 'ペルー', en: 'Peru' },
  { ja: 'フィリピン', en: 'Philippines' },
  { ja: 'ポーランド', en: 'Poland' },
  { ja: 'ポルトガル', en: 'Portugal' },
  { ja: 'カタール', en: 'Qatar' },
  { ja: 'ルーマニア', en: 'Romania' },
  { ja: 'ロシア', en: 'Russia' },
  { ja: 'ルワンダ', en: 'Rwanda' },
  { ja: 'サウジアラビア', en: 'Saudi Arabia' },
  { ja: 'セネガル', en: 'Senegal' },
  { ja: 'シエラレオネ', en: 'Sierra Leone' },
  { ja: 'シンガポール', en: 'Singapore' },
  { ja: 'ソマリア', en: 'Somalia' },
  { ja: '南アフリカ', en: 'South Africa' },
  { ja: '南スーダン', en: 'South Sudan' },
  { ja: 'スペイン', en: 'Spain' },
  { ja: 'スリランカ', en: 'Sri Lanka' },
  { ja: 'スーダン', en: 'Sudan' },
  { ja: 'スリナム', en: 'Suriname' },
  { ja: 'スウェーデン', en: 'Sweden' },
  { ja: 'スイス', en: 'Switzerland' },
  { ja: 'シリア', en: 'Syria' },
  { ja: '台湾', en: 'Taiwan' },
  { ja: 'タジキスタン', en: 'Tajikistan' },
  { ja: 'タンザニア', en: 'Tanzania' },
  { ja: 'タイ', en: 'Thailand' },
  { ja: '東ティモール', en: 'Timor-Leste' },
  { ja: 'トーゴ', en: 'Togo' },
  { ja: 'トリニダード・トバゴ', en: 'Trinidad and Tobago' },
  { ja: 'チュニジア', en: 'Tunisia' },
  { ja: 'トルコ', en: 'Turkey' },
  { ja: 'トルクメニスタン', en: 'Turkmenistan' },
  { ja: 'ウガンダ', en: 'Uganda' },
  { ja: 'ウクライナ', en: 'Ukraine' },
  { ja: 'アラブ首長国連邦', en: 'United Arab Emirates' },
  { ja: 'イギリス', en: 'United Kingdom' },
  { ja: 'アメリカ', en: 'United States' },
  { ja: 'ウルグアイ', en: 'Uruguay' },
  { ja: 'ウズベキスタン', en: 'Uzbekistan' },
  { ja: 'ベネズエラ', en: 'Venezuela' },
  { ja: 'ベトナム', en: 'Vietnam' },
  { ja: 'イエメン', en: 'Yemen' },
  { ja: 'ザンビア', en: 'Zambia' },
  { ja: 'ジンバブエ', en: 'Zimbabwe' },
];

// 日本語 or 英語テキストから英語国名を返す
export function normalizeCountry(text) {
  if (!text) return null;
  const t = text.trim();
  // 日本語で前方/部分一致
  const byJa = COUNTRIES.find(c => t.includes(c.ja) || c.ja.includes(t));
  if (byJa) return byJa.en;
  // 英語で部分一致（大文字小文字無視）
  const byEn = COUNTRIES.find(c => t.toLowerCase().includes(c.en.toLowerCase()) || c.en.toLowerCase().includes(t.toLowerCase()));
  if (byEn) return byEn.en;
  return t; // マッチしなければそのまま
}
